//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenericRepostiory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class manager
    {
        public byte WORKER_REF_ID { get; set; }
        public string WORKER_TITLE { get; set; }
        public Nullable<System.DateTime> AFFECTED_FROM { get; set; }
    
        public virtual worker worker { get; set; }


        public override string ToString()
        {
            return "Worker Title : "+ WORKER_TITLE;
        }
    }
}
