//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenericRepostiory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class worker
    {
        public byte WORKER_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public Nullable<int> SALARY { get; set; }
        public Nullable<System.DateTime> JOINTNG_DATE { get; set; }
        public string DEPARTMENT { get; set; }
    
        public virtual manager manager { get; set; }

        public override string ToString()
        {
            return "WorkerId : " + WORKER_ID + " , FirstName : " +FIRST_NAME +" , LastName : "+LAST_NAME;
        }
    }
}
